prjsmallWorld_core/smallWorld/Models/CLogin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smallWorld.Models
{
    public class CLogin
    {
        public string fAccount { get; set; }

        public string fPassword { get; set; }
    }
}

prjsmallWorld_core/smallWorld/Models/CRegister.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace smallWorld.Models
{
    public class CRegister
    {
        [Key]
        public int fMemberId { get; set; }

        [Display(Name = "帳號")]
        [Required(ErrorMessage = "請輸入帳號")]
        public string fAccount { get; set; }

        [Display(Name ="密碼")]
        [Required(ErrorMessage = "請輸入密碼")]
        [DataType(DataType.Password)]
        public string fPassword { get; set; }

        [Display(Name ="再次輸入密碼")]
        [Required(ErrorMessage ="請再次輸入密碼")]
        [Compare("fPassword",ErrorMessage ="密碼不一致")]
        [DataType(DataType.Password)]
        public string fPassword_confirm { get; set; }

        [Display(Name = "姓名")]
        [Required(ErrorMessage = "請輸入姓名")]
        public string fName { get; set; }

        [Display(Name = "生日")]
        [Required(ErrorMessage = "請輸入生日")]
        [DataType(DataType.Date)]
        public DateTime fBirthday { get; set; }

        [Display(Name = "信箱")]
        [Required(ErrorMessage = "請輸入信箱")]
        [DataType(DataType.EmailAddress)]
        public string fEmail { get; set; }

        public DateTime fBuildtime { get; set; }

        public string fAuthcode { get; set; }
    }
}

prjsmallWorld_core/smallWorld/Models/ErrorViewModel.cs
using System;

namespace smallWorld.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

prjsmallWorld_core/smallWorld/Models/db.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace smallWorld.Models
{

    public class db
    {
        SqlConnection con = new SqlConnection("Data Source=LAPTOP-49GQ7CD1\\SQLEXPRESS;Initial Catalog=dbCustomer;Integrated Security=True");
        public int LoginCheck(CLogin c)
        {
            SqlCommand cmd = new SqlCommand("SP_Login",con);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@fAccount",c.fAccount);
            cmd.Parameters.AddWithValue("@fPassword", c.fPassword);
            SqlParameter objlogin = new SqlParameter();
            objlogin.ParameterName = "@Isvalid";
            objlogin.SqlDbType = SqlDbType.Bit;
            objlogin.Direction = ParameterDirection.Output;
            cmd.Parameters.Add(objlogin);
            con.Open();
            cmd.ExecuteNonQuery();
            int res = Convert.ToInt32(objlogin.Value);
            con.Close();
            return res;
        }
    }
}

prjsmallWorld_core/smallWorld/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using smallWorld.Models;

namespace smallWorld.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        db db = new db();

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index([Bind] CLogin c)
        {
            int res = db.LoginCheck(c);
            if (res == 1)
                TempData["msg"] = "歡迎登入";
            else
                TempData["msg"] = "帳號或密碼錯誤，請重來";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

prjsmallWorld_core/smallWorld/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using smallWorld.Models;

namespace smallWorld.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CRegister member)
        {
            string connection = "Data Source=LAPTOP-49GQ7CD1\\SQLEXPRESS;Initial Catalog=dbCustomer;Integrated Security=True";
            using (SqlConnection con = new SqlConnection(connection))
            {
                string sqlQuery = $@"Insert into Member(fAccount,fPassword,fName,fBirthday,fEmail,fBuildtime)
                    values ('{member.fAccount}','{member.fPassword}','{member.fName}',
'{member.fBirthday.ToString("yyyy-MM-dd")}','{member.fEmail}','{DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")}')";
                using (SqlCommand cmd = new SqlCommand(sqlQuery, con))
                {
                    con.Open();
                    cmd.ExecuteNonQuery();
                    ViewData["Message"] = "會員" +"  "+member.fName + "  " +  "註冊成功...!";
                }
            }
                return View(member);
        }
    }
}

prjsmallWorld_core/smallWorld/Views/Home/Index.cshtml
@model smallWorld.Models.CLogin
@{
    ViewData["Title"] = "會員登入頁";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>會員登入</h1>

<h4>請輸入帳號密碼登入管理頁面</h4>
<hr />
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <form asp-action="Index">
                <div class="form-group">
                    <label class="custom-control-label">帳號</label>
                    <input type="text" asp-for="fAccount" class="form-control" />
                </div>
                <div class="form-group">
                    <label class="custom-control-label">密碼</label>
                    <input type="password" asp-for="fPassword" class="form-control" />
                </div>
                <div class="form-group">
                    <input type="submit" value="送出" />
                </div>
            </form>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>

@{

    if (TempData["msg"] != null)
    {
        <script>
            alert('@TempData["msg"]')
        </script>
    }
}

prjsmallWorld_core/smallWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - smallWorld</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        ul {
            list-style:none;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">smallWorld</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">登入</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">註冊</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - smallWorld - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

prjsmallWorld_core/smallWorld/Views/User/Create.cshtml
@model smallWorld.Models.CRegister

@{
    ViewData["Title"] = "會員註冊頁";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>會員註冊頁</h1>

<h4>歡迎註冊，輸入以下資訊加入我們</h4>
<b class="text-danger">@ViewData["Message"]</b>
<hr />
<div class="row">
    <div class="col-md-9">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="fAccount" class="control-label"></label>
                <input asp-for="fAccount" class="form-control" />
                <span asp-validation-for="fAccount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fPassword" class="control-label"></label>
                <input asp-for="fPassword" class="form-control" />
                <span asp-validation-for="fPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fPassword_confirm" class="control-label"></label>
                <input asp-for="fPassword_confirm" class="form-control" />
                <span asp-validation-for="fPassword_confirm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fName" class="control-label"></label>
                <input asp-for="fName" class="form-control" />
                <span asp-validation-for="fName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fBirthday" class="control-label"></label>
                <input asp-for="fBirthday" class="form-control" />
                <span asp-validation-for="fBirthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fEmail" class="control-label"></label>
                <input asp-for="fEmail" class="form-control" />
                <span asp-validation-for="fEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="註冊" class="btn btn-primary" />
            </div>
            
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}